---
abstract: 'Basic API to SugarSync cloud file sharing.'
author:
  - 'Johan Vromans <jv@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SugarSync-API
provides:
  SugarSync::API:
    file: lib/SugarSync/API.pm
    version: 0.06
requires:
  Carp: 0
  Config::Tiny: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Path: 0
  Getopt::Long: 0
  LWP::UserAgent: 0
  Time::Local: 0
  XML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
